
image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview
    visibility: public

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y xfce4 xfce4-goodies tightvncserver
      vncserver :1 -geometry 1280x800 -depth 24
    command: |
      vncserver :1 -geometry 1280x800 -depth 24
